# Generated by Django 3.1.2 on 2020-10-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appThree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=264),
        ),
    ]
